# Generated by Django 5.0.2 on 2024-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('PassengerId', models.IntegerField(primary_key=True, serialize=False)),
                ('Pclass', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Sex', models.CharField(max_length=10)),
                ('Age', models.FloatField(blank=True, null=True)),
                ('SibSp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Ticket', models.CharField(max_length=50)),
                ('Fare', models.FloatField(blank=True, null=True)),
                ('Cabin', models.CharField(blank=True, max_length=50, null=True)),
                ('Embarked', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
