# Generated by Django 5.0.2 on 2024-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('document_link', models.URLField(blank=True)),
            ],
        ),
    ]
