# Generated by Django 5.0.2 on 2024-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='fips_199',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='iscp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='pia',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='sap',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='sar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='ssp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
