# Generated by Django 5.0.2 on 2024-03-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_standard_fips_199_standard_iscp_standard_pia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poam_id', models.CharField(max_length=255)),
                ('scan_id', models.CharField(max_length=255)),
                ('assets_impacted', models.CharField(max_length=255)),
                ('vulnerability_name', models.CharField(max_length=255)),
                ('vulnerability_source', models.CharField(max_length=255)),
                ('initial_risk_rating', models.CharField(max_length=255)),
                ('original_detection_date', models.DateField()),
                ('tool_vulnerability_description', models.TextField()),
                ('tool_recommended_action', models.TextField()),
                ('csp_vulnerability_information', models.TextField(blank=True)),
            ],
        ),
    ]
