# Generated by Django 5.0.2 on 2024-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_drdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drdata',
            name='assets_impacted',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='csp_vulnerability_information',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='initial_risk_rating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='original_detection_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='poam_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='scan_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='tool_recommended_action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='tool_vulnerability_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='vulnerability_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drdata',
            name='vulnerability_source',
            field=models.CharField(max_length=100),
        ),
    ]
